//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinecone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelFilmovaContainer : DbContext
    {
        public ModelFilmovaContainer()
            : base("name=ModelFilmovaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Films> FilmsSet { get; set; }
        public virtual DbSet<Zanrs> ZanrsSet { get; set; }
        public virtual DbSet<Glumacs> GlumacsSet { get; set; }
        public virtual DbSet<GlumacFilm> GlumacFilmSet { get; set; }
        public virtual DbSet<ZanrFilm> ZanrFilmSet { get; set; }
    }
}
