//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinecone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZanrFilm
    {
        public int Film_Id { get; set; }
        public int Zanr_Id { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Zanrs Zanrs { get; set; }
    }
}
